Update release workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -9,9 +9,54 @@ on:
       version_number:
         description: 'Release Version Number (Eg, v1.0.0)'
         required: true
+      delete_existing_tag_release:
+        description: 'Is this a re-release of existing tag/release? (Default: false)'
+        default: 'false'
+        required: false
+
+env:
+  repository_compressed_name: ${{ github.event.repository.name }}-${{ github.event.inputs.version_number }}
+  repository_zip_name: ${{ github.event.repository.name }}-${{ github.event.inputs.version_number }}.zip
+  # Some library use different name for library and repository. Version number may use library_name in source file.
+  library_name: "FreeRTOS+TCP"
+  # Source folder list for version number updates
+  source_folder_list: "source test"
 
 jobs:
-  tag-commit:
+  clean-existing-tag-and-release:
+    if: ${{ github.event.inputs.delete_existing_tag_release == 'true' }}
+    runs-on: ubuntu-latest
+    env:
+      VERSION_NUM: ${{ github.event.inputs.version_number }}
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Check if tag exists
+        run: |
+          git fetch origin
+          if git tag --list $VERSION_NUM
+          then
+              echo "Deleting existing tag for $VERSION_NUM"
+              git push origin --delete tags/$VERSION_NUM
+          fi
+
+      - name: Check if release exists
+        run: |
+          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key 23F3D4EA75716059
+          sudo apt-add-repository https://cli.github.com/packages
+          sudo apt update
+          sudo apt-get install gh
+          if gh release list | grep $VERSION_NUM
+          then
+              echo "Deleting existing release for $VERSION_NUM"
+              gh release delete --yes $VERSION_NUM
+          fi
+
+  add-sbom-and-tag-commit:
+    if: ${{ ( github.event.inputs.delete_existing_tag_release == 'true' && success() )  || ( github.event.inputs.delete_existing_tag_release == 'false' && always() ) }}
+    needs: clean-existing-tag-and-release
     name: Tag commit
     runs-on: ubuntu-latest
     steps:
@@ -19,85 +64,187 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: ${{ github.event.inputs.commit_id }}
+
       - name: Configure git identity
         run: |
           git config --global user.name ${{ github.actor }}
           git config --global user.email ${{ github.actor }}@users.noreply.github.com
+
       - name: create a new branch that references commit id
         run: git checkout -b ${{ github.event.inputs.version_number }} ${{ github.event.inputs.commit_id }}
+
+      - name: Update version number in source files
+        run: |
+            echo "${{ env.source_folder_list }}" | \
+            xargs -n 1 sh -c \
+            'find $1 -type f \( -name "*.c" -o -name "*.h" \) \
+            -exec sed -i -b -E "0,/^ \* ${{ env.library_name }}/s/^ \* ${{ env.library_name }}.*/ \* ${{ env.library_name }} ${{ github.event.inputs.version_number }}/g" {} +'
+            git add .
+            git commit -m '[AUTO][RELEASE]: Update version number in source files'
+            git push -u origin ${{ github.event.inputs.version_number }}
+
+      - name : Update version number in manifest.yml
+        run: |
+          sed -i -b '0,/^version/s/^version.*/version: "${{ github.event.inputs.version_number }}"/g' ./manifest.yml
+          git add .
+          git commit -m '[AUTO][RELEASE]: Update version number in manifest.yml'
+          git push -u origin ${{ github.event.inputs.version_number }}
+
+      - name : Update version number in doxygen
+        run: |
+          sed -i -b 's/PROJECT_NUMBER *=.*/PROJECT_NUMBER         = ${{ github.event.inputs.version_number }}/g' ./docs/doxygen/config.doxyfile
+          git add .
+          git commit -m '[AUTO][RELEASE]: Update version number in doxygen'
+          git push -u origin ${{ github.event.inputs.version_number }}
+
+      - name : Update MQTT version number macro
+        if: ${{ github.event.repository.name == 'coreMQTT' }}
+        run: |
+          sed -i -b 's/^\#define MQTT_LIBRARY_VERSION .*/\#define MQTT_LIBRARY_VERSION    "${{ github.event.inputs.version_number }}"/g' source/include/core_mqtt.h
+          git add .
+          git commit -m '[AUTO][RELEASE]: Update version number macro in source/include/core_mqtt.h'
+          git push -u origin ${{ github.event.inputs.version_number }}
+
       - name: Generate SBOM
         uses: FreeRTOS/CI-CD-Github-Actions/sbom-generator@main
         with:
           repo_path: ./
           source_path: ./source
+
       - name: commit SBOM file
         run: |
           git add .
           git commit -m 'Update SBOM'
           git push -u origin ${{ github.event.inputs.version_number }}
+
       - name: Tag Commit and Push to remote
         run: |
-          git tag ${{ github.event.inputs.version_number }} -a -m "FreeRTOS-Plus-TCP Library ${{ github.event.inputs.version_number }}"
+          git tag ${{ github.event.inputs.version_number }} -a -m "${{ github.event.repository.name }} Library ${{ github.event.inputs.version_number }}"
           git push origin --tags
+
       - name: Verify tag on remote
         run: |
           git tag -d ${{ github.event.inputs.version_number }}
           git remote update
           git checkout tags/${{ github.event.inputs.version_number }}
           git diff ${{ github.event.inputs.commit_id }} tags/${{ github.event.inputs.version_number }}
+
   create-zip:
-    needs: tag-commit
+    if: ${{ ( github.event.inputs.delete_existing_tag_release == 'true' && success() )  || ( github.event.inputs.delete_existing_tag_release == 'false' && always() ) }}
+    needs: add-sbom-and-tag-commit
     name: Create ZIP and verify package for release asset.
     runs-on: ubuntu-latest
     steps:
       - name: Install ZIP tools
         run: sudo apt-get install zip unzip
+
       - name: Checkout code
         uses: actions/checkout@v4
         with:
-          ref: ${{ github.event.inputs.commit_id }}
-          path: FreeRTOS-Plus-TCP
+          ref: ${{ github.event.inputs.version_number }}
+          path: ${{ github.event.repository.name }}
           submodules: recursive
+
       - name: Checkout disabled submodules
         run: |
-          cd FreeRTOS-Plus-TCP
+          cd ${{ github.event.repository.name }}
           git submodule update --init --checkout --recursive
+
       - name: Create ZIP
         run: |
-          zip -r FreeRTOS-Plus-TCP-${{ github.event.inputs.version_number }}.zip FreeRTOS-Plus-TCP -x "*.git*"
+          zip -r ${{ env.repository_zip_name }} ${{ github.event.repository.name }} -x "*.git*"
           ls ./
+
       - name: Validate created ZIP
         run: |
           mkdir zip-check
-          mv FreeRTOS-Plus-TCP-${{ github.event.inputs.version_number }}.zip zip-check
+          mv ${{ env.repository_zip_name }} zip-check
           cd zip-check
-          unzip FreeRTOS-Plus-TCP-${{ github.event.inputs.version_number }}.zip -d FreeRTOS-Plus-TCP-${{ github.event.inputs.version_number }}
-          ls FreeRTOS-Plus-TCP-${{ github.event.inputs.version_number }}
-          diff -r -x "*.git*" FreeRTOS-Plus-TCP-${{ github.event.inputs.version_number }}/FreeRTOS-Plus-TCP/ ../FreeRTOS-Plus-TCP/
+          unzip ${{ env.repository_zip_name }} -d ${{ env.repository_compressed_name }}
+          ls ${{ env.repository_compressed_name }}
+          diff -r -x "*.git*" ${{ env.repository_compressed_name }}/${{ github.event.repository.name }}/ ../${{ github.event.repository.name }}/
           cd ../
+
+      - name: Check version number in source files
+        run: |
+          cd zip-check/${{ env.repository_compressed_name }}/${{ github.event.repository.name }}
+
+          # List all the *.h *.c files in <source_folder_list>
+          SOURCE_FILE_LIST=$( echo "${{ env.source_folder_list }}" | \
+          xargs -n 1 sh -c 'find $1 -type f \( -name "*.c" -o -name "*.h" \)' )
+
+          # List all the files which contain " * <repository_name>.*" in SOURCE_FILE_LIST
+          SOURCE_FILE_WITH_VERSION_LIST=$( grep -l " \* ${{ github.event.repository.name }}.*" $SOURCE_FILE_LIST )
+
+          # Compare the <version_number> with input version number in files in SOURCE_FILE_LIST
+          echo $SOURCE_FILE_WITH_VERSION_LIST | xargs -I{} sh -c \
+          'grep -x " \* ${{ github.event.repository.name }} ${{ github.event.inputs.version_number }}" {} && \
+          echo {} : match ${{ github.event.repository.name }} ${{ github.event.inputs.version_number }} || \
+          { echo "{} : ${{ github.event.repository.name }} ${{ github.event.inputs.version_number }} not found"; exit 255; }'
+
+      - name: Check version number in doxygen
+        run: |
+          cd zip-check/${{ env.repository_compressed_name }}/${{ github.event.repository.name }}
+
+          # find "PROJECT_NUMBER = <version_number>"
+          DOXYGEN_VERSION_NUMBER=$(grep -x "[ ]*PROJECT_NUMBER[ ]*=[ ]*[^ ]*[ ]*" docs/doxygen/config.doxyfile | awk -F= '{gsub(" ","",$2); print $2 }');
+
+          # compare the <version_number> with input version number
+          [[ $DOXYGEN_VERSION_NUMBER == "${{ github.event.inputs.version_number }}" ]] \
+          && echo "config.doxyfile : match ${{ github.event.inputs.version_number }}" \
+          || { echo "config.doxyfile : $DOXYGEN_VERSION_NUMBER doesn't match ${{ github.event.inputs.version_number }}"; exit 255; }
+
+      - name: Check version number in manifest.yml
+        run: |
+          cd zip-check/${{ env.repository_compressed_name }}/${{ github.event.repository.name }}
+
+          # find the first occurence of "version: <version_number>" and comare the <version_number> with input version number
+          MANIFEST_VESION_NUMBER=$( grep -m 1 -E "^version:[ ]*\".*\"[ ]*" manifest.yml | awk -F: '{ gsub(" ","",$2); gsub("\"","",$2); print $2 }' );
+
+          # compare the <version_number> with input version number
+          [[ $MANIFEST_VESION_NUMBER == "${{ github.event.inputs.version_number }}" ]] \
+          && echo "manifest.yml : match ${{ github.event.inputs.version_number }}" \
+          || { echo "manifest.yml : $MANIFEST_VESION_NUMBER doesn't match ${{ github.event.inputs.version_number }}"; exit 255; }
+
+      - name: Check MQTT version number macro in header file
+        if: ${{ github.event.repository.name == 'coreMQTT' }}
+        run: |
+          cd zip-check/${{ env.repository_compressed_name }}/${{ github.event.repository.name }}
+
+          # find "#define MQTT_LIBRARY_VERSION <version_number>" in core_mqtt.h
+          MACRO_VERSION_NUMBER=$(grep -x "^\#define[ ]*MQTT_LIBRARY_VERSION[ ]*\".*\"[ ]*" source/include/core_mqtt.h | awk '{gsub("\"","",$3); print $3 }');
+          
+          # compare the <version_number> with input version number
+          [[ $MACRO_VERSION_NUMBER == "${{ github.event.inputs.version_number }}" ]] \
+          && echo "core_mqtt.h : match ${{ github.event.inputs.version_number }}" \
+          || { echo "core_mqtt.h : $MACRO_VERSION_NUMBER doesn't match ${{ github.event.inputs.version_number }}"; exit 255; }
+
       - name: Build
         run: |
-          cd zip-check/FreeRTOS-Plus-TCP-${{ github.event.inputs.version_number }}/FreeRTOS-Plus-TCP
+          cd zip-check/${{ env.repository_compressed_name }}/${{ github.event.repository.name }}
           sudo apt-get install -y lcov
           sudo apt-get install unifdef
           cmake -S test/unit-test -B test/unit-test/build/
           make -C test/unit-test/build/ all
       - name: Test
         run: |
-          cd zip-check/FreeRTOS-Plus-TCP-${{ github.event.inputs.version_number }}/FreeRTOS-Plus-TCP
+          cd zip-check/${{ env.repository_compressed_name }}/${{ github.event.repository.name }}
           pushd test/unit-test/build/
           ctest -E system --output-on-failure
           popd
           make -C test/unit-test/build/ coverage
           lcov --list --rc lcov_branch_coverage=1 test/unit-test/build/coverage.info
           cd ..
+
       - name: Create artifact of ZIP
         uses: actions/upload-artifact@v4
         with:
-          name: FreeRTOS-Plus-TCP-${{ github.event.inputs.version_number }}.zip
-          path: zip-check/FreeRTOS-Plus-TCP-${{ github.event.inputs.version_number }}.zip
+          name: ${{ env.repository_zip_name }}
+          path: zip-check/${{ env.repository_zip_name }}
+
   deploy-doxygen:
-    needs: tag-commit
+    needs: add-sbom-and-tag-commit
+    if: ${{ ( github.event.inputs.delete_existing_tag_release == 'true' && success() )  || ( github.event.inputs.delete_existing_tag_release == 'false' && always() ) }}
     name: Deploy doxygen documentation
     runs-on: ubuntu-latest
     steps:
@@ -106,10 +253,12 @@ jobs:
         with:
           ref: ${{ github.event.inputs.version_number }}
           add_release: "true"
+
   create-release:
     needs:
       - create-zip
       - deploy-doxygen
+    if: ${{ ( github.event.inputs.delete_existing_tag_release == 'true' && success() )  || ( github.event.inputs.delete_existing_tag_release == 'false' && always() ) }}
     name: Create Release and Upload Release Asset
     runs-on: ubuntu-latest
     steps:
@@ -121,13 +270,15 @@ jobs:
         with:
           tag_name: ${{ github.event.inputs.version_number }}
           release_name: ${{ github.event.inputs.version_number }}
-          body: Release ${{ github.event.inputs.version_number }} of the FreeRTOS-Plus-TCP Library.
+          body: Release ${{ github.event.inputs.version_number }} of the ${{ github.event.repository.name }} Library.
           draft: false
           prerelease: false
+
       - name: Download ZIP artifact
         uses: actions/download-artifact@v4
         with:
-          name: FreeRTOS-Plus-TCP-${{ github.event.inputs.version_number }}.zip
+          name: ${{ env.repository_zip_name }}
+
       - name: Upload Release Asset
         id: upload-release-asset
         uses: actions/upload-release-asset@v1
@@ -135,8 +286,8 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./FreeRTOS-Plus-TCP-${{ github.event.inputs.version_number }}.zip
-          asset_name: FreeRTOS-Plus-TCP-${{ github.event.inputs.version_number }}.zip
+          asset_path: ./${{ env.repository_zip_name }}
+          asset_name: ${{ env.repository_zip_name }}
           asset_content_type: application/zip
   cleanup:
     needs:
